services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: wedding-backend
    env_file:
      - ./apps/backend/.env
    ports:
      - "5001:5001"

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: wedding-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
